### ISSUE TITLE
Screen: Motion Graphic Video 

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-design-2017#13] opened 2017-07-21 18:40 UTC
### Description:
This video will be on loop playing motion graphics on screens around the building displaying festival information.

Content TBD such as:
- MozFest 2017 Brand
- Tagline
- Spaces 
- Speaker Series (times, talk, speaker, location)
- #mozhelp + info desk
- Social Media (hashtags, handles, platforms)
- WiFi (network, password)
- Schedule App

### Reference from Last Year: 
Google Drive File: https://drive.google.com/file/d/0B20-0lpP23c0dmJBNjFSc1hSMjA/view
Github Issue: https://github.com/MozillaFoundation/Mozfest2016_production/issues/170

__________________________
#### Deadline
GanttStart: 2017-09-04
GanttDue: 2017-09-29

**Comment by edrushka** [comment] 2017-09-12 23:38
Can also highlight Artists in Residence (1 per slide, listing what space you can find them in). That info is available here: https://github.com/mozilla/mozillafestival.org/issues/724

**Comment by edrushka** [comment] 2017-09-12 23:39
Can also add individual points from the participation guidelines (1 point per slide). That info is here:
https://github.com/mozilla/mozillafestival.org/issues/703

**Comment by edrushka** [comment] 2017-09-12 23:46
Would be great to include localized versions of tagline, too.

**Comment by sabrinang** [comment] 2017-09-29 21:58
@natalieworth and I outlined content in this google doc: https://docs.google.com/a/mozilla.com/document/d/1onZKZsAwrS73qyDPiAeiT1jDcTBVXBjFfynxySBxGTs/edit?usp=sharing

**Comment by edrushka** [comment] 2017-10-02 22:24
Also, link to Sam B.'s forthcoming Attitudes About Internet Health report
@KevZawacki @Lottarao do you have an ETA for this link? We'll be finalizing these slides on Oct 13.

**Comment by edrushka** [comment] 2017-10-02 22:25
Also, lunch times for each day. Both days lunch is from 12:00 - 2:00

**Comment by KevZawacki** [comment] 2017-10-03 13:35
@edrushka I've just asked Sam B. what the URL will be. Update to come...

**Comment by natalieworth** [comment] 2017-10-03 22:19
Hey @sabrinang @edrushka I've got a super rough draft/ low-res version of the screen vid here: https://drive.google.com/drive/folders/0B20-0lpP23c0LVJGWmIyX1JTUUU?usp=sharing

There's no animation, transitions, design, etc. yet. It's more just to figure out the content and what is needed still, but feel free to add or leave feedback if I've missed anything:
P1
- [x] finalize content by October 13
- [x] get images of the artists in residence
- [x] floor numbers if possible (e.g. web literacy, digital inclusion, etc. for wayfinding on screens)
- [x] Internet health slide design/ content from Sam B.
- [x] add list of speaker series (rotating)
- [x] mozilla/ pulse, instagram, and facebook icons under 'connect on social'

P2
- [ ] localized tag line
- [ ] fix timing
- [ ] add subtle and accent animations
- [ ] adjust colours, design, type if necessary
- [ ] slide transitions
- [ ] brand check from Sabrina at end
- [x] add wave plugin in After Effects (trapcode)

**Comment by edrushka** [comment] 2017-10-04 00:34
Ohhh lovely! 🌷 May I suggest as a P2 replacing the words "email" and "call" on the participation guidelines slide with icons? It feels like a lot of text on that slide.

Also, as P1, please add a slide that says:   Lunch 12:00-2:00 

@marcwalsh do you have lunch locations confirmed, and also tagging you so you can see these slides in progress!

**Comment by KevZawacki** [comment] 2017-10-05 20:41
@edrushka The link to Sam B.'s forthcoming Attitudes About Internet Health report will be https://mzl.la/attitudes

**Comment by edrushka** [comment] 2017-10-05 20:46
Lunch locations have been confirmed: Ground Floor, 4th Floor, 7th Floor

If you want to make a slide about coffee locations (P2) it will be served in the Walker Space on the Ground Floor, Floor 5 and Floor 9

**Comment by natalieworth** [comment] 2017-10-16 21:52
@sabrinang @edrushka Do you know where I'm able to grab the artist in residence photos? If they haven't sent them to us yet, we could just go with text maybe due to time?

**Comment by sabrinang** [comment] 2017-10-16 21:58
@natalieworth For the festival guide Cassie used them and here's the links folder for the festival guide: https://drive.google.com/open?id=0B4Q8pzCpDS_ea1BZakN6bE1aVkU

You will have to find their names but they have a purple overlay on their photos and should be labelled with the artists name

**Comment by natalieworth** [comment] 2017-10-17 00:44
@sabrinang @edrushka Have a rough V2 here with all the p1's added with the exception of the Speaker Series rotation [mozfest-screen-draft-v3.mov](https://drive.google.com/drive/folders/0B20-0lpP23c0LVJGWmIyX1JTUUU)

**Comment by edrushka** [comment] 2017-10-17 10:48
mozfest-screen-draft-v3.mov is looking really good. Love the artist slides. My only comment is the "are you seeing disrespectful behaviour" feels super intense on that red background. Any way to tone that down?

**Comment by natalieworth** [comment] 2017-10-17 18:57
@edrushka Yeah for sure! I'll swap out the red so it's less intense

**Comment by xmatthewx** [comment] 2017-10-19 15:51
I noticed a URL typo. (this video is amazing! the waves are crazy). @natalieworth - the url for pulse is `mozillapulse.org`, not mozilla dot pulse.

**Comment by natalieworth** [comment] 2017-10-21 01:50
Hey @sabrinang @edrushka Have v4 of the [video up here ](https://drive.google.com/drive/folders/0B20-0lpP23c0LVJGWmIyX1JTUUU?usp=sharing) I've got all the copy in now. I haven't had time yet to add that much movement/ animation. Hoping to get to that next week if I get time (sorry, been super busy with the Advocacy site launching soon! :S )

**Comment by edrushka** [comment] 2017-10-21 14:00
❤️ the Speaker Series slide - nicely done.

**Comment by sabrinang** [comment] 2017-10-22 21:57
This is looking great @natalieworth! For the speaker slides, do you have that as an .ai file? I would love to use that hexagon quilt for a title card when we stream it.

@edrushka The only content that stands out looking over this is the social slide. For instagram, are we going to active on the mozillagram account? If not, perhaps a hashtag instead like #mozfest2017 or something would be more effective. As for facebook live, where do people actually go (is it the official https://www.facebook.com/mozilla/ page)? Also, I think twitter is the most active https://twitter.com/mozillafestival and could promote that here as well 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/2492510/31866680-ea5dfeae-b737-11e7-831f-87bc2bb73202.png">

**Comment by edrushka** [comment] 2017-10-23 09:30
@tlasadea @KevZawacki are these the links you'd like to see for social? (These are for the internal, 'mini-net' screens throughout the building)

**Comment by KevZawacki** [comment] 2017-10-23 09:40
I think it'd be wise to include #mozfest2017 — but defer to @tlasadea!

**Comment by tlasadea** [comment] 2017-10-23 10:21
Hey! @sabrinang @edrushka links for social are Twitter - @mozillafestival and the hashtag is just #mozfest 💯

**Comment by edrushka** [comment] 2017-10-23 10:25
@tlasadea do you want instagram and fb live as well?

**Comment by tlasadea** [comment] 2017-10-23 10:30
Hmmmmm...these displays are gonna be in and around Ravensbourne right? If so, don't need FB Live. and the hashtag can work on Twitter & Instagram!

So for copy could we have @sabrinang:

Use #MozFest on Twitter & Instagram 

Twitter @MozillaFestival 
Instagram @Mozillagram

Is that ok?

**Comment by edrushka** [comment] 2017-10-23 10:48
Works for me! @natalieworth can you make those changes?

**Comment by edrushka** [comment] 2017-10-25 11:45
@natalieworth when this is ready, can you please send to @EsmeSimcox here or via email? She will send on to the team at Ravensbourne.

**Comment by edrushka** [comment] 2017-10-25 12:22
Hi again @natalieworth - can you please remove Arachana's slide (yellow one in the artist series) as she is no longer able to attend - before you export the final version? thanks

**Comment by natalieworth** [comment] 2017-10-26 10:04
@EsmeSimcox I'm just uploading the final file onto the google drive here: https://drive.google.com/drive/folders/0B20-0lpP23c0S1BRZ25KTllHanc?usp=sharing

cc @sabrinang Ack so the 'Trapcode' plugin trial expired and wouldn't let me export the line backgrounds—so I swaped in the MozFest logo. Less pretty but hopefully it's okay still! Sorry!

cc @edrushka If you have time to double check the final file above for me that would be great too! Ty!

**Comment by edrushka** [comment] 2017-10-26 11:33
@natalieworth we're not seeing anything in GDrive - did the upload complete?

**Comment by natalieworth** [comment] 2017-10-26 11:37
@edrushka Sorry still uploading! The file's quite large and the wifi is sloowwww 😆😱 I'll post on here when it's uploaded!

**Comment by natalieworth** [comment] 2017-10-26 13:46
@sabrinang @edrushka do you have a USB maybe? It's taking forever to upload since the wifi is so slow. I could bring my laptop to Ravensbourne and we could just transfer it directly?

**Comment by edrushka** [comment] 2017-10-26 14:56
@marcwalsh who at Rave needs the video file to program the mini-net? Can you put them in touch with Natalie to transfer the file directly?

**Comment by natalieworth** [comment] 2017-10-27 12:17
@edrushka @EsmeSimcox @sabrinang Got some faster wifi at the Moz London office. Uploaded here now! https://drive.google.com/drive/folders/0B20-0lpP23c0S1BRZ25KTllHanc?usp=sharing

**Comment by edrushka** [comment] 2017-10-27 13:42
Yay! I've sent to Rave to program the mini-nets. Closing this ticket - will re-open if there are any issues with the file. Thanks all - this will look gorgeous in the building 😍

**Closed as completed by edrushka** 2017-10-27 13:42 UTC
Labels: Digital
